name: Ruby Tests with Coverage

on:
  pull_request:
  push:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.1'
          bundler-cache: true

      - name: Install dependencies
        run: bundle install

      - name: Run tests with coverage
        run: bundle exec rspec

      - name: Check SimpleCov coverage
        uses: alexremn/simplecov-github-action@v1
        with:
          minimum_suite_coverage: 95
          minimum_file_coverage: 90
          on_fail_status: warn  # Won't fail the workflow even if coverage is low
          post_comment: true    # Post results as a PR comment
          github_token: ${{ secrets.GITHUB_TOKEN }}

      # Optional: Upload coverage report as an artifact
      - name: Upload coverage report
        uses: actions/upload-artifact@v4
        with:
          name: coverage-report
          path: coverage
          retention-days: 7
